blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://support.lifplatforms.com
    about: Need community support? Visit out community forums where people are willing, ready, and able to help.
